#!/usr/bin/python3
# file: simsys.py
# content: system simulator
# created: 2020 july 19 Sunday
# modified:
# modification:
# author: roch schanen
# comment: system architecture simulator

# todo: make signals
# todo: make bus
# todo: make engine
# todo: make processor
# todo: make memory
# todo: make devices
# todo: make time, records, etc... 
# todo: break point, step-by-step, state display

# collect every device in the system
# run system engine and record data

from numpy.random import randint as rnd
from time import strftime 
from sys import exit

# FOR COMPATIBILLTY ISSUES

SEP = " "    # SIGNAL SEPARATOR
EOL = "\n"   # END-OF-LINE CODE

# SIGNAL COUNTER

N = 0

# SYSTEM / MODULE #########################################

class system():

    # (generic)
    def __init__(self, name):
        date = strftime("%A, %d %b %Y at %H:%M:%S")
        print(f"create system {name}\n{date}")
        self.devicelist = {}
        self.name = name
        self.date = date
        self.time = 0
        # done
        return

    # (generic)
    def getName(self, generic):
        n, k = 0, f"{generic}0"
        while k in self.devicelist.keys():
            n += 1
            k = f"{generic}{n}"
        # found name
        return k

    # (generic)
    def displayDevices(self):
        for d in self.devicelist.values(): d.display()            
        return

    # (generic)
    def openFile(self, pathName = "./output.vcd"):
        # create file
        fh = open(pathName, 'w')
        # make header
        fh.write(f"$version Generated by simsys.py $end{EOL}")
        fh.write(f"$date {self.date} $end{EOL}")
        fh.write(f"$timescale 1ns $end{EOL}")
        # make modules and signals
        fh.write(f"$scope module SYSTEM $end{EOL}")
        for d in self.devicelist.values(): d.makeModule(fh, 0)
        fh.write(f"$upscope $end{EOL}")
        # close header
        fh.write(f"$enddefinitions $end{EOL}")
        # done
        self.pathName = pathName
        self.fh = fh
        return

    # (generic)
    def closeFile(self):
        self.fh.close()
        return

    # (generic)
    def runStep(self):
        # export new state
        exportResult = ""
        for device in self.devicelist.values():
            exportResult += device.export()
        # export
        if exportResult:
            self.fh.write(f"#{self.time}")
            self.fh.write(f"{SEP}{exportResult}{EOL}")
        # increase time by step interval [ns]
        self.time += 1
        # update device outputs
        for device in self.devicelist.values():
            device.updateOutputPorts(self.time)
        # update device inputs
        for device in self.devicelist.values():
            device.updateInputPorts()        
        # done
        return

    # (generic)
    def runUntil(self, time):
        while self.time < time:
            self.runStep()
        return

    # (specific)
    # time units are in ns (float) 
    def addClock( 
        self,
        period = 20,    # 20ns, 50MHz
        width  = 10,    # symetrical clock
        phase  = 0,     # 0ns, in phase
        name   = None): # None, generic name
        # check duplicate
        if name in self.devicelist.keys():
            print(f"system.addClock: clock name duplicate.")
            print(f"  name {name} already used.")
            print(f"  exiting...")
            exit()
        # get generic clock name
        if not name: name = self.getName("clr")
        # create
        self.devicelist[name] = \
            clock(period, width, phase, name)
        # done
        return self.devicelist[name]

    # (specific)
    # time units are in ns (float) 
    def addCounter( 
        self,
        size = 4,     # 4, half a byte
        name = None): # None, generic name
        # check duplicate
        if name in self.devicelist.keys():
            print(f"system.addClock: clock name duplicate.")
            print(f"  name {name} already used.")
            print(f"  exiting...")
            exit()
        # get generic counter name
        if not name: name = self.getName("cnt")
        # create
        self.devicelist[name] = \
            counter(size, name)
        # done
        return self.devicelist[name]


# PORT COMMON #############################################

class portCommon():

    def addSignal(self):
        global N
        self.signal = f"W{N}"
        N += 1
        return self.signal

    def get(self):
        return self.state

    def size(self):
        return len(self.state)

    # export to VCD format
    def export(self):
        if self.signal:
            # no change
            if self.uptodate: return ""
            # set flag
            self.uptodate = True
            # bit string export
            if self.size() > 1:
                return f"b{self.state} {self.signal}{SEP}"
            # single bit export
            return f"{self.state}{self.signal}{SEP}"
        # no signal
        return ""

# OUTPUT PORTS ############################################

class outPort(portCommon):

    def __init__(self, bits = 1, name = None):
        # initialise to undefined value 'U'
        self.state = 'U'*bits
        # register port name
        self.name = name
        # force update at origin
        self.uptodate = False
        # export signal
        self.signal = None
        return

    def set(self, newvalue):
        # check type is string 
        if not isinstance(newvalue, str):
            print(f"port.set: value must be of string type.")
            print(f"  exiting...")
            exit()
        # check size
        if not len(newvalue) == self.size():
            print(f"port.set: value size mismatch:")
            print(f"  value size is {len(value)}.")
            print(f"  expected size is {self.size()}.")
            print(f"  exiting...")
            exit()
        # set flag
        self.uptodate = (self.state == newvalue)
        # update value
        self.state = newvalue
        # done
        return

# INPUT PORTS #############################################

class inPort(portCommon):

    def __init__(self, port, name = None):
        # linking (adding to the network)
        self.p = port
        # register port name
        self.name = name
        # initial state
        self.state = port.get()
        # force update at origin
        self.uptodate = False
        # export signal
        self.signal = None
        # clear edge events        
        self.rising  = False
        self.falling = False
        return

    def update(self):
        newvalue = self.p.get()
        # update flag
        self.uptodate = (self.state == newvalue)
        # update value
        if self.p.size() > 1:
            self.state = newvalue
            return
        # single bit case        
        self.rising  = False
        self.falling = False
        # detect rising edge
        if (self.state, newvalue) == ('0','1'):
            self.rising = True                 
        # detect falling edge
        if (self.state, newvalue) == ('1','0'):
            self.falling = True
        # update state
        self.state = newvalue                 
        return


# DEVICE #################################################

class Device():

    def __init__(self,
            name):  # device name
        self.name = name
        self.inports  = []
        self.outports = []
        self.exports  = []
        return

    def writeVar(self,
            f,  # file
            t,  # tab level
            p): # port
        # write port signal
        if p.name:
            # register port in export list
            self.exports.append(p)
            # get size
            size = p.size()
            # get signal name
            label = f"{self.name}_{p.name}"
            if size > 1:
                label += f"[{size-1}:0]"
            # get signal identifier
            signal = p.addSignal()
            f.write(f"{t}\t$var")    # header
            f.write(f" wire {size}") # signal size
            f.write(f" {signal}")    # signal identifier
            f.write(f" {label}")     # signal name
            f.write(f" $end{EOL}")   # tail
        return

    def makeModule(self,
            f,  # file
            t): # tab level
        # get module name
        name = self.name
        # tab alignment
        tab  = '\t'*(t+1)
        # write header
        f.write(f"{tab}$scope module {name} $end{EOL}")
        # write variables (inputs)
        for p in self.inports:
            self.writeVar(f, tab, p)
        # write variables (outputs)
        for p in self.outports:
            self.writeVar(f, tab, p)
        # write tail
        f.write(f"{tab}$upscope $end{EOL}")
        # done
        return

    def updateInputPorts(self):
        for p in self.inports: p.update()
        return

    def export(self):
        exportResult = ""
        for p in self.exports:
            exportResult += p.export()
        return exportResult


# COUNTER #################################################

# todo: counter options
# clr on active low, high
# trg on rising, falling edge
# wrt on active low, high
# ena on active low, high
# cse on active low, high
# initial value random, zero, maybe undefined
# maybe parallel, serial load

class counter(Device):

    # activated when input connected
    clr = None # clear   (reset)
    trg = None # trigger (clock)
    # wrt = None # write   (load
    # ena = None # enable  (output)
    # cse = None # chip select

    def __init__(self,
            size,   # counter bits width 
            name):  # counter name
        # call parent class constructor
        Device.__init__(self, name)
        # record data
        self.name = name
        self.configuration = size
        # instanciate output port
        self.Q = outPort(size, "Q")
        # register port
        self.outports.append(self.Q)
        # set default output port value
        self.Q.set(f'{rnd(size):0{size}b}')
        return

    def addTrigger(self,
            p): # port
        # instanciate input port
        self.trg = inPort(p, "trg")
        # register port
        self.inports.append(self.trg)
        return

    def addClear(self,
            p): # port
        # instanciate input port
        self.clr = inPort(p, "clr")
        # register port
        self.inports.append(self.clr)
        return

    def display(self):
        name = self.name
        size = self.configuration
        value = self.Q.get()
        # display
        print(f"CNT: {name},{size},{value}")
        return

    def updateOutputPorts(self, timeStamp):
        # get configuration
        size = self.configuration
        # asynchronous clear on active low
        if self.clr.state == '0':
            # clear ouput
            self.Q.set(f'{0:0{size}b}')
            return
        # update on rising edge of trigger
        if self.trg.rising:
            # get incremented state
            n = int(self.Q.get(), 2) + 1
            # make n string, LSB(size) only
            newvalue = f'{n:0{size}b}'[-size:]
            # new output
            self.Q.set(newvalue)
            return
        # done
        return

# CLOCK ###################################################

class clock(Device):

    def __init__(
            self,
            period, # clock period (float time)
            width,  # pulse width  (float time)
            phase,  # phase shift  (float time)
            name):  # clock name
        # call parent class constructor
        Device.__init__(self, name)
        # record data
        self.name = name
        self.configuration = period, width, phase
        # instanciate output port
        self.Q = outPort(1, "Q")
        # register port
        self.outports.append(self.Q)
        # setup output port high
        self.Q.set('1')
        # done
        return

    def display(self):
        name = self.name
        period, width, phase = self.configuration
        value = self.Q.get()
        # display
        print(f"CLK: {name},{period},{width},{phase},{value}")
        return

    def updateOutputPorts(self, timeStamp):
        # get configuration
        period, width, phase = self.configuration
        # get new state
        m = (timeStamp-phase) % period
        newvalue = ['0','1'][m < width]
        # update output
        self.Q.set(newvalue)        
        # done
        return

# BUILD ###################################################

if __name__ == "__main__":

    import sys

    print("file: simsys.py")
    print("content: system simulator")
    print("created: 2020 july 19 Sunday")
    print("author: roch schanen")
    print("comment: system architecture simulator")
    print("run Python3:" + sys.version);

    # instanciate simulator
    mySystem = system("version 0.00")
    # instanciate a port of size 1:
    # add a button key to show on the waves 
    myResetButton = outPort(1)

    # instanciate a clock
    myclock = mySystem.addClock()
    
    # instanciate a counter
    myCounter = mySystem.addCounter()
    
    # make counter inputs network
    myCounter.addTrigger(myclock.Q)
    myCounter.addClear(myResetButton)
    
    # show all devices
    mySystem.displayDevices()
    
    # open export file
    mySystem.openFile()
    
    # run simulator    
    myResetButton.set('0')
    mySystem.runUntil(15)
    myResetButton.set('1')
    mySystem.runUntil(250)
    
    # close export file
    mySystem.closeFile()
